import pandas as pd 

traducao = {
    'Abkhazia': 'Abecásia',
    'Afghanistan': 'Afeganistão',
    'Albania': 'Albânia',
    'Alderney': 'Alderney',
    'Algeria': 'Argélia',
    'American Samoa': 'Samoa Americana',
    'Andalusia': 'Andaluzia',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Anguilla': 'Anguilla',
    'Antigua and Barbuda': 'Antígua e Barbuda',
    'Arameans Suryoye': 'Arameus Suryoye',
    'Argentina': 'Argentina',
    'Armenia': 'Armênia',
    'Artsakh': 'Artsakh',
    'Aruba': 'Aruba',
    'Australia': 'Austrália',
    'Austria': 'Áustria',
    'Aymara': 'Aymara',
    'Azerbaijan': 'Azerbaijão',
    'Bahamas': 'Bahamas',
    'Bahrain': 'Bahrein',
    'Bangladesh': 'Bangladesh',
    'Barawa': 'Barawa',
    'Barbados': 'Barbados',
    'Basque Country': 'País Basco',
    'Belarus': 'Bielorrússia',
    'Belgium': 'Bélgica',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bermuda': 'Bermudas',
    'Bhutan': 'Butão',
    'Biafra': 'Biafra',
    'Bolivia': 'Bolívia',
    'Bonaire': 'Bonaire',
    'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
    'Botswana': 'Botsuana',
    'Brazil': 'Brasil',
    'British Virgin Islands': 'Ilhas Virgens Britânicas',
    'Brittany': 'Bretanha',
    'Brunei': 'Brunei',
    'Bulgaria': 'Bulgária',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cambodia': 'Camboja',
    'Cameroon': 'Camarões',
    'Canada': 'Canadá',
    'Canary Islands': 'Ilhas Canárias',
    'Cape Verde': 'Cabo Verde',
    'Cascadia': 'Cascádia',
    'Catalonia': 'Catalunha',
    'Cayman Islands': 'Ilhas Cayman',
    'Central African Republic': 'República Centro-Africana',
    'Central Spain': 'Espanha Central',
    'Chad': 'Chade',
    'Chagos Islands': 'Ilhas Chagos',
    'Chameria': 'Chaméria',
    'Chile': 'Chile',
    'China PR': 'China',
    'Colombia': 'Colômbia',
    'Comoros': 'Comores',
    'Congo': 'Congo',
    'Cook Islands': 'Ilhas Cook',
    'Corsica': 'Córsega',
    'Costa Rica': 'Costa Rica',
    'County of Nice': 'Condado de Nice',
    'Croatia': 'Croácia',
    'Cuba': 'Cuba',
    'Curaçao': 'Curaçao',
    'Cyprus': 'Chipre',
    'Czech Republic': 'República Tcheca',
    'Czechoslovakia': 'Tchecoslováquia',
    'DR Congo': 'República Democrática do Congo',
    'Darfur': 'Darfur',
    'Denmark': 'Dinamarca',
    'Djibouti': 'Djibuti',
    'Dominica': 'Dominica',
    'Dominican Republic': 'República Dominicana',
    'Ecuador': 'Equador',
    'Egypt': 'Egito',
    'El Salvador': 'El Salvador',
    'Ellan Vannin': 'Ellan Vannin',
    'England': 'Inglaterra',
    'Equatorial Guinea': 'Guiné Equatorial',
    'Eritrea': 'Eritreia',
    'Estonia': 'Estônia',
    'Eswatini': 'Eswatini',
    'Ethiopia': 'Etiópia',
    'Falkland Islands': 'Ilhas Malvinas',
    'Faroe Islands': 'Ilhas Faroé',
    'Felvidék': 'Felvidék',
    'Fiji': 'Fiji',
    'Finland': 'Finlândia',
    'France': 'França',
    'French Guiana': 'Guiana Francesa',
    'Frøya': 'Frøya',
    'Gabon': 'Gabão',
    'Galicia': 'Galícia',
    'Gambia': 'Gâmbia',
    'Georgia': 'Geórgia',
    'German DR': 'Alemanha Oriental',
    'Germany': 'Alemanha',
    'Ghana': 'Gana',
    'Gibraltar': 'Gibraltar',
    'Gotland': 'Gotland',
    'Gozo': 'Gozo',
    'Greece': 'Grécia',
    'Greenland': 'Groenlândia',
    'Grenada': 'Granada',
    'Guadeloupe': 'Guadalupe',
    'Guam': 'Guam',
    'Guatemala': 'Guatemala',
    'Guernsey': 'Guernsey',
    'Guinea': 'Guiné',
    'Guinea-Bissau': 'Guiné-Bissau',
    'Guyana': 'Guiana',
    'Găgăuzia': 'Gagauzia',
    'Haiti': 'Haiti',
    'Hitra': 'Hitra',
    'Hmong': 'Hmong',
    'Honduras': 'Honduras',
    'Hong Kong': 'Hong Kong',
    'Hungary': 'Hungria',
    'Iceland': 'Islândia',
    'India': 'Índia',
    'Indonesia': 'Indonésia',
    'Iran': 'Irã',
    'Iraq': 'Iraque',
    'Iraqi Kurdistan': 'Curdistão Iraquiano',
    'Isle of Man': 'Ilha de Man',
    'Isle of Wight': 'Ilha de Wight',
    'Israel': 'Israel',
    'Italy': 'Itália',
    'Ivory Coast': 'Costa do Marfim',
    'Jamaica': 'Jamaica',
    'Japan': 'Japão',
    'Jersey': 'Jersey',
    'Jordan': 'Jordânia',
    'Kabylia': 'Cabilia',
    'Kazakhstan': 'Cazaquistão',
    'Kenya': 'Quênia',
    'Kernow': 'Kernow',
    'Kiribati': 'Kiribati',
    'Kosovo': 'Kosovo',
    'Kuwait': 'Kuwait',
    'Kyrgyzstan': 'Quirguistão',
    'Kárpátalja': 'Cárpatos',
    'Laos': 'Laos',
    'Latvia': 'Letônia',
    'Lebanon': 'Líbano',
    'Lesotho': 'Lesoto',
    'Liberia': 'Libéria',
    'Libya': 'Líbia',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lituânia',
    'Luxembourg': 'Luxemburgo',
    'Macau': 'Macau',
    'Madagascar': 'Madagascar',
    'Madrid': 'Madri',
    'Malawi': 'Malawi',
    'Malaysia': 'Malásia',
    'Maldives': 'Maldivas',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Manchukuo': 'Manchukuo',
    'Mapuche': 'Mapuche',
    'Martinique': 'Martinica',
    'Matabeleland': 'Matabeleland',
    'Mauritania': 'Mauritânia',
    'Mauritius': 'Maurício',
    'Mayotte': 'Mayotte',
    'Menorca': 'Menorca',
    'Mexico': 'México',
    'Micronesia': 'Micronésia',
    'Moldova': 'Moldávia',
    'Monaco': 'Mônaco',
    'Mongolia': 'Mongólia',
    'Montenegro': 'Montenegro',
    'Montserrat': 'Montserrat',
    'Morocco': 'Marrocos',
    'Mozambique': 'Moçambique',
    'Myanmar': 'Mianmar',
    'Namibia': 'Namíbia',
    'Nepal': 'Nepal',
    'Netherlands': 'Holanda',
    'New Caledonia': 'Nova Caledônia',
    'New Zealand': 'Nova Zelândia',
    'Nicaragua': 'Nicarágua',
    'Niger': 'Níger',
    'Nigeria': 'Nigéria',
    'Niue': 'Niue',
    'North Korea': 'Coreia do Norte',
    'North Macedonia': 'Macedônia do Norte',
    'North Vietnam': 'Vietnã do Norte',
    'Northern Cyprus': 'Chipre do Norte',
    'Northern Ireland': 'Irlanda do Norte',
    'Northern Mariana Islands': 'Ilhas Marianas do Norte',
    'Norway': 'Noruega',
    'Occitania': 'Ocitânia',
    'Oman': 'Omã',
    'Orkney': 'Órcades',
    'Padania': 'Padânia',
    'Pakistan': 'Paquistão',
    'Palau': 'Palau',
    'Palestine': 'Palestina',
    'Panama': 'Panamá',
    'Panjab': 'Panjabe',
    'Papua New Guinea': 'Papua-Nova Guiné',
    'Paraguay': 'Paraguai',
    'Parishes of Jersey': 'Paróquias de Jersey',
    'Peru': 'Peru',
    'Philippines': 'Filipinas',
    'Poland': 'Polônia',
    'Portugal': 'Portugal',
    'Provence': 'Provença',
    'Puerto Rico': 'Porto Rico',
    'Qatar': 'Catar',
    'Raetia': 'Récia',
    'Republic of Ireland': 'Irlanda',
    'Republic of St. Pauli': 'República de St. Pauli',
    'Rhodes': 'Rodes',
    'Romani people': 'Povo Romani',
    'Romania': 'Romênia',
    'Russia': 'Rússia',
    'Rwanda': 'Ruanda',
    'Réunion': 'Reunião',
    'Saare County': 'Condado de Saare',
    'Saarland': 'Sarre',
    'Saint Helena': 'Santa Helena',
    'Saint Kitts and Nevis': 'São Cristóvão e Nevis',
    'Saint Lucia': 'Santa Lúcia',
    'Saint Martin': 'São Martinho',
    'Saint Pierre and Miquelon': 'Saint Pierre e Miquelon',
    'Saint Vincent and the Grenadines': 'São Vicente e Granadinas',
    'Samoa': 'Samoa',
    'San Marino': 'San Marino',
    'Sark': 'Sark',
    'Saudi Arabia': 'Arábia Saudita',
    'Scotland': 'Escócia',
    'Senegal': 'Senegal',
    'Serbia': 'Sérvia',
    'Seychelles': 'Seicheles',
    'Shetland': 'Shetland',
    'Sierra Leone': 'Serra Leoa',
    'Silesia': 'Silesia',
    'Singapore': 'Singapura',
    'Sint Maarten': 'Sint Maarten',
    'Slovakia': 'Eslováquia',
    'Slovenia': 'Eslovênia',
    'Solomon Islands': 'Ilhas Salomão',
    'Somalia': 'Somália',
    'Somaliland': 'Somalilândia',
    'South Africa': 'África do Sul',
    'South Korea': 'Coreia do Sul',
    'South Ossetia': 'Ossétia do Sul',
    'South Sudan': 'Sudão do Sul',
    'Spain': 'Espanha',
    'Sri Lanka': 'Sri Lanka',
    'Sudan': 'Sudão',
    'Suriname': 'Suriname',
    'Sweden': 'Suécia',
    'Switzerland': 'Suíça',
    'Syria': 'Síria',
    'Székely Land': 'Terra Székely',
    'Sápmi': 'Sápmi',
    'São Tomé and Príncipe': 'São Tomé e Príncipe',
    'Tahiti': 'Taiti',
    'Taiwan': 'Taiwan',
    'Tajikistan': 'Tajiquistão',
    'Tamil Eelam': 'Tâmil Eelam',
    'Tanzania': 'Tanzânia',
    'Thailand': 'Tailândia',
    'Tibet': 'Tibete',
    'Ticino': 'Ticino',
    'Timor-Leste': 'Timor-Leste',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinidad e Tobago',
    'Tunisia': 'Tunísia',
    'Turkey': 'Turquia',
    'Turkmenistan': 'Turcomenistão',
    'Turks and Caicos Islands': 'Ilhas Turks e Caicos',
    'Tuvalu': 'Tuvalu',
    'Uganda': 'Uganda',
    'Ukraine': 'Ucrânia',
    'United Arab Emirates': 'Emirados Árabes Unidos',
    'United Koreans in Japan': 'Coreanos Unidos no Japão',
    'United States': 'Estados Unidos',
    'United States Virgin Islands': 'Ilhas Virgens Americanas',
    'Uruguay': 'Uruguai',
    'Uzbekistan': 'Uzbequistão',
    'Vanuatu': 'Vanuatu',
    'Vatican City': 'Cidade do Vaticano',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Vietnã',
    'Vietnam Republic': 'República do Vietnã',
    'Wales': 'País de Gales',
    'Wallis Islands and Futuna': 'Ilhas Wallis e Futuna',
    'Western Armenia': 'Armênia Ocidental',
    'Western Australia': 'Austrália Ocidental',
    'Western Isles': 'Ilhas Ocidentais',
    'Western Sahara': 'Saara Ocidental',
    'Yemen': 'Iêmen',
    'Yemen DPR': 'Iêmen do Sul',
    'Ynys Môn': 'Ynys Môn',
    'Yorkshire': 'Yorkshire',
    'Yoruba Nation': 'Nação Yoruba',
    'Yugoslavia': 'Iugoslávia',
    'Zambia': 'Zâmbia',
    'Zanzibar': 'Zanzibar',
    'Zimbabwe': 'Zimbábue',
    'Åland Islands': 'Ilhas Åland',
    'Friendly': 'Amistoso',
    'British Home Championship': 'Campeonato Britânico em Casa',
    'Évence Coppée Trophy': 'Troféu Évence Coppée',
    'Copa Lipton': 'Copa Lipton',
    'Copa Newton': 'Copa Newton',
    'Copa Premio Honor Argentino': 'Copa Prêmio de Honra Argentino',
    'Copa Premio Honor Uruguayo': 'Copa Prêmio de Honra Uruguaio',
    'Copa Roca': 'Copa Roca',
    'Copa América': 'Copa América',
    'Copa Chevallier Boutell': 'Copa Chevallier Boutell',
    'Nordic Championship': 'Campeonato Nórdico',
    'Central European International Cup': 'Copa Internacional da Europa Central',
    'Baltic Cup': 'Copa Báltica',
    'Balkan Cup': 'Copa dos Balcãs',
    'FIFA World Cup': 'Copa do Mundo FIFA',
    'Copa Rio Branco': 'Copa Rio Branco',
    'FIFA World Cup qualification': 'Eliminatórias da Copa do Mundo FIFA',
    'Bolivarian Games': 'Jogos Bolivarianos',
    'CCCF Championship': 'Campeonato da CCCF',
    'NAFC Championship': 'Campeonato da NAFC',
    'Copa Oswaldo Cruz': 'Copa Oswaldo Cruz',
    'Pan American Championship': 'Campeonato Pan-Americano',
    'Copa del Pacífico': 'Copa do Pacífico',
    "Copa Bernardo O'Higgins": 'Copa Bernardo O\'Higgins',
    'AFC Asian Cup qualification': 'Eliminatórias da Copa Asiática',
    'Atlantic Cup': 'Copa Atlântica',
    'AFC Asian Cup': 'Copa Asiática',
    'African Cup of Nations': 'Copa Africana das Nações',
    'Copa Paz del Chaco': 'Copa Paz del Chaco',
    'Merdeka Tournament': 'Torneio Merdeka',
    'UEFA Euro qualification': 'Eliminatórias da Eurocopa',
    'UEFA Euro': 'Eurocopa',
    'Windward Islands Tournament': 'Torneio das Ilhas de Sotavento',
    'African Cup of Nations qualification': 'Eliminatórias da Copa Africana das Nações',
    'Vietnam Independence Cup': 'Copa da Independência do Vietnã',
    'Copa Carlos Dittborn': 'Copa Carlos Dittborn',
    'Phillip Seaga Cup': 'Copa Phillip Seaga',
    'CONCACAF Championship': 'Campeonato da CONCACAF',
    'Copa Juan Pinto Durán': 'Copa Juan Pinto Durán',
    'Arab Cup': 'Copa Árabe',
    'South Pacific Games': 'Jogos do Pacífico Sul',
    'CONCACAF Championship qualification': 'Eliminatórias do Campeonato da CONCACAF',
    'Copa Artigas': 'Copa Artigas',
    'GaNEFo': 'GaNEFo',
    "King's Cup": 'Copa do Rei',
    'Gulf Cup': 'Copa do Golfo',
    'Indonesia Tournament': 'Torneio da Indonésia',
    'Korea Cup': 'Copa da Coreia',
    'Palestine Cup': 'Copa da Palestina',
    'Brazil Independence Cup': 'Copa da Independência do Brasil',
    'Copa Ramón Castilla': 'Copa Ramón Castilla',
    'Oceania Nations Cup': 'Copa das Nações da Oceania',
    'CECAFA Cup': 'Copa CECAFA',
    'Kuneitra Cup': 'Copa Kuneitra',
    'Copa Félix Bogado': 'Copa Félix Bogado',
    'Real Madrid 75th Anniversary Cup': 'Copa de Aniversário de 75 anos do Real Madrid',
    'Beijing International Friendship Tournament': 'Torneio Internacional de Amizade de Pequim',
    'Kirin Cup': 'Copa Kirin',
    'CFU Caribbean Cup qualification': 'Eliminatórias da Copa do Caribe da CFU',
    'CFU Caribbean Cup': 'Copa do Caribe da CFU',
    'Amílcar Cabral Cup': 'Copa Amílcar Cabral',
    'FIFA 75th Anniversary Cup': 'Copa de Aniversário de 75 anos da FIFA',
    'Guangzhou International Friendship Tournament': 'Torneio Internacional de Amizade de Guangzhou',
    'Mundialito': 'Mundialito',
    'West African Cup': 'Copa da África Ocidental',
    'Nehru Cup': 'Copa Nehru',
    'Merlion Cup': 'Copa Merlion',
    'Great Wall Cup': 'Copa da Grande Muralha',
    'UDEAC Cup': 'Copa da UDEAC',
    'Rous Cup': 'Copa Rous',
    'CONMEBOL–UEFA Cup of Champions': 'Copa dos Campeões CONMEBOL-UEFA',
    'Lunar New Year Cup': 'Copa do Ano Novo Lunar',
    'Arab Cup qualification': 'Eliminatórias da Copa Árabe',
    'Tournoi de France': 'Torneio da França',
    'Malta International Tournament': 'Torneio Internacional de Malta',
    'Matthews Cup': 'Copa Matthews',
    'Tournament Burkina Faso': 'Torneio do Burkina Faso',
    'Island Games': 'Jogos das Ilhas',
    'NAFU Championship': 'Campeonato da NAFU',
    'Dynasty Cup': 'Copa Dynasty',
    'Dakar Tournament': 'Torneio de Dakar',
    'UNCAF Cup': 'Copa UNCAF',
    'Gold Cup': 'Copa Ouro',
    'USA Cup': 'Copa dos EUA',
    'Jordan International Tournament': 'Torneio Internacional da Jordânia',
    'Confederations Cup': 'Copa das Confederações',
    'United Arab Emirates Friendship Tournament': 'Torneio de Amizade dos Emirados Árabes Unidos',
    'Oceania Nations Cup qualification': 'Eliminatórias da Copa das Nações da Oceania',
    'Simba Tournament': 'Torneio Simba',
    'SAFF Cup': 'Copa SAFF',
    'AFF Championship': 'Campeonato AFF',
    'King Hassan II Tournament': 'Torneio do Rei Hassan II',
    'Cyprus International Tournament': 'Torneio Internacional do Chipre',
    'Dunhill Cup': 'Copa Dunhill',
    'COSAFA Cup qualification': 'Eliminatórias da COSAFA Cup',
    'COSAFA Cup': 'COSAFA Cup',
    'Gold Cup qualification': 'Eliminatórias da Copa Ouro',
    'SKN Football Festival': 'Festival de Futebol SKN',
    'UNIFFAC Cup': 'Copa UNIFFAC',
    'WAFF Championship': 'Campeonato WAFF',
    'Millennium Cup': 'Copa do Milênio',
    'Cup of Ancient Civilizations': 'Copa das Civilizações Antigas',
    "Prime Minister's Cup": 'Copa do Primeiro Ministro',
    'EAFF Championship': 'Campeonato da EAFF',
    'TIFOCO Tournament': 'Torneio TIFOCO',
    'Afro-Asian Games': 'Jogos Afro-Asiáticos',
    'AFC Challenge Cup': 'Copa Desafio da AFC',
    'FIFI Wild Cup': 'Copa FIFI Wild',
    'ELF Cup': 'Copa ELF',
    'Viva World Cup': 'Copa Viva World',
    'AFC Challenge Cup qualification': 'Eliminatórias da Copa Desafio da AFC',
    'African Nations Championship': 'Campeonato Africano das Nações',
    'VFF Cup': 'Copa VFF',
    'Dragon Cup': 'Copa do Dragão',
    'ABCS Tournament': 'Torneio ABCS',
    'Nile Basin Tournament': 'Torneio da Bacia do Nilo',
    'Nations Cup': 'Copa das Nações',
    'Copa Confraternidad': 'Copa da Confraternidade',
    'Pacific Games': 'Jogos do Pacífico',
    'Superclásico de las Américas': 'Superclássico das Américas',
    'Kirin Challenge Cup': 'Copa Desafio Kirin',
    'OSN Cup': 'Copa OSN',
    'CONIFA World Football Cup': 'Copa do Mundo de Futebol CONIFA',
    'CONIFA European Football Cup': 'Copa Europeia de Futebol CONIFA',
    'Copa América qualification': 'Eliminatórias da Copa América',
    'World Unity Cup': 'Copa da Unidade Mundial',
    'Pacific Mini Games': 'Mini Jogos do Pacífico',
    'Intercontinental Cup': 'Copa Intercontinental',
    'AFF Championship qualification': 'Eliminatórias do Campeonato AFF',
    'UEFA Nations League': 'Liga das Nações da UEFA',
    'CONCACAF Nations League qualification': 'Eliminatórias da Liga das Nações da CONCACAF',
    'African Nations Championship qualification': 'Eliminatórias do Campeonato Africano das Nações',
    'Atlantic Heritage Cup': 'Copa do Patrimônio Atlântico',
    'Inter Games Football Tournament': 'Torneio de Futebol Inter Jogos',
    'CONCACAF Nations League': 'Liga das Nações da CONCACAF',
    'Three Nations Cup': 'Copa das Três Nações',
    'Mahinda Rajapaksa Cup': 'Copa Mahinda Rajapaksa',
    'Navruz Cup': 'Copa Navruz',
    'CONIFA Africa Football Cup': 'Copa Africana de Futebol CONIFA',
    'CONIFA South America Football Cup': 'Copa Sul-Americana de Futebol CONIFA',
    "MSG Prime Minister's Cup": 'Copa do Primeiro Ministro MSG',
    'Tri Nation Tournament': 'Torneio das Três Nações',
    'CAFA Nations Cup': 'Copa das Nações da CAFA',
    'Mauritius Four Nations Cup': 'Copa das Quatro Nações de Maurício',
    'CONIFA World Football Cup qualification': 'Eliminatórias da Copa do Mundo de Futebol CONIFA',
    'CONIFA Asia Cup': 'Copa da Ásia CONIFA',
    'All' : 'Todas Competições'
}

def formata_df(df, team):
    print(df['tournament'].unique())
    df = formata_datas(df)

    filter = (df["home_team"] == team) | (df["away_team"] == team)
    filter_home = df["country"] == team
    filter_away = df["country"] != team

    df = df[filter]
    df['decade'] = (df['year'] // 10) * 10
    df['result'] = df.apply(lambda row: determinar_resultado(row, team), axis=1)
    df['opponent'] = df.apply(lambda row: determinar_adversario(row, team), axis=1)
    df['GP'] = 0
    df['GS'] = 0

    for index, row in df.iterrows():
        decade = row['decade']
        home_score = row['home_score']
        away_score = row['away_score']

        # Atualize GP e GC
        if row['home_team'] == team:
            df.loc[index, 'GP'] += home_score
            df.loc[index, 'GS'] += away_score
        elif row['away_team'] == team:
            df.loc[index, 'GP'] += away_score
            df.loc[index, 'GS'] += home_score

    df_home = df[filter_home]
    df_away = df[filter_away]

    return df, df_home, df_away

#Funçao para definir resultado do jogo -> Vitória, Empate ou Derrota
def determinar_resultado(row, team):
    if row['home_score'] > row['away_score'] and row["home_team"] == team:
        return 'Vitória'
    elif row['home_score'] < row['away_score'] and row["home_team"] == team:
        return 'Derrota'
    elif row['home_score'] > row['away_score'] and row["away_team"] == team:
        return 'Derrota'
    elif row['home_score'] < row['away_score'] and row["away_team"] == team:
        return 'Vitória'
    elif row['home_score'] == row['away_score']:
        return 'Empate'

#Função para definir adversário
def determinar_adversario(row, team):
    if row['home_team'] == team:
      return row['away_team']
    else:
      return row['home_team']

#Função para formatar datas
def formata_datas(df):
    df['date'] = pd.to_datetime(df['date'])
    df['year'] = df['date'].dt.year
    return df

def traduz_paises(df):
    df['home_team'] = df['home_team'].map(traduz)
    df['away_team'] = df['away_team'].map(traduz)
    df['tournament'] = df['tournament'].map(traduz)
    df['country'] = df['country'].map(traduz)
    return df

# Função para mapear os valores
def traduz(nome):
    if nome in traducao:
        return traducao[nome]
    return nome  # Se não houver tradução, retorna o mesmo nome


def resultado_por_oponente(df):

    resultados = pd.DataFrame()
    resultados['Vitória'] = (df['result'] == 'Vitória').groupby(df['opponent']).sum()
    resultados['Derrota'] = (df['result'] == 'Derrota').groupby(df['opponent']).sum()
    resultados['Empate'] = (df['result'] == 'Empate').groupby(df['opponent']).sum()
    resultados['Número de Jogos'] = df.groupby('opponent')['result'].count()

    resultados = resultados.fillna(0)
    resultados['Percentual Vitórias'] = (resultados['Vitória'] / resultados['Número de Jogos']) * 100
    resultados['Percentual Derrotas'] = (resultados['Derrota'] / resultados['Número de Jogos']) * 100
    resultados['Percentual Empates'] = (resultados['Empate'] / resultados['Número de Jogos']) * 100
    resultados['Percentual Vitórias'] = resultados['Percentual Vitórias'].round(2)
    resultados['Percentual Derrotas'] = resultados['Percentual Derrotas'].round(2)
    resultados['Percentual Empates'] = resultados['Percentual Empates'].round(2)

    resultados = resultados.sort_values(by='Número de Jogos', ascending=False)
    resultados = resultados.head(10)
    resultados = resultados.sort_values(by=['Percentual Vitórias', 'Percentual Empates', 'Percentual Derrotas'], ascending=True)

    return resultados